/**
 * Normalized platform manifest derived from platforms.csv
 * (MobyGames platform reference, header: platform,gamesCount,...).
 *
 * Generated once; do not hand-edit. To regenerate, re-run the
 * derivation against platforms.csv and update the drift test in
 * tests/platform-manifest/. Entries carry no provider ids: the
 * reference file provides none, and ids are never invented.
 */
import type { PlatformManifestEntry } from './platform-manifest.js';

export const PLATFORM_MANIFEST: readonly PlatformManifestEntry[] = [
  { source: 'mobygames', name: '1292 Advanced Programmable Video System', expectedGames: 56 },
  { source: 'mobygames', name: '3DO', expectedGames: 256 },
  { source: 'mobygames', name: 'ABC 80', expectedGames: 1 },
  { source: 'mobygames', name: 'Acorn 32-bit', expectedGames: 249 },
  { source: 'mobygames', name: 'Adventure Vision', expectedGames: 4 },
  { source: 'mobygames', name: 'AirConsole', expectedGames: 6 },
  { source: 'mobygames', name: 'Alice 32/90', expectedGames: 8 },
  { source: 'mobygames', name: 'Altair 680', expectedGames: 1 },
  { source: 'mobygames', name: 'Altair 8800', expectedGames: 105 },
  { source: 'mobygames', name: 'Amazon Alexa', expectedGames: 132 },
  { source: 'mobygames', name: 'Amiga', expectedGames: 3996 },
  { source: 'mobygames', name: 'Amiga CD32', expectedGames: 187 },
  { source: 'mobygames', name: 'Amstrad CPC', expectedGames: 2364 },
  { source: 'mobygames', name: 'Amstrad PCW', expectedGames: 126 },
  { source: 'mobygames', name: 'Android', expectedGames: 14076 },
  { source: 'mobygames', name: 'Antstream', expectedGames: 1196 },
  { source: 'mobygames', name: 'APF MP1000/Imagination Machine', expectedGames: 14 },
  { source: 'mobygames', name: 'Apple I', expectedGames: 10 },
  { source: 'mobygames', name: 'Apple II', expectedGames: 2997 },
  { source: 'mobygames', name: 'Apple IIgs', expectedGames: 220 },
  { source: 'mobygames', name: 'Arcade', expectedGames: 3653 },
  { source: 'mobygames', name: 'Arcadia 2001', expectedGames: 36 },
  { source: 'mobygames', name: 'Arduboy', expectedGames: 34 },
  { source: 'mobygames', name: 'Astral 2000', expectedGames: 1 },
  { source: 'mobygames', name: 'Atari 2600', expectedGames: 676 },
  { source: 'mobygames', name: 'Atari 5200', expectedGames: 95 },
  { source: 'mobygames', name: 'Atari 7800', expectedGames: 86 },
  { source: 'mobygames', name: 'Atari 8-bit', expectedGames: 2229 },
  { source: 'mobygames', name: 'Atari ST', expectedGames: 2527 },
  { source: 'mobygames', name: 'Atari VCS', expectedGames: 106 },
  { source: 'mobygames', name: 'Atom', expectedGames: 38 },
  { source: 'mobygames', name: 'Auto Response Board', expectedGames: 3 },
  { source: 'mobygames', name: 'bada', expectedGames: 94 },
  { source: 'mobygames', name: 'Bally Astrocade', expectedGames: 29 },
  { source: 'mobygames', name: 'Bandai RX-78 Gundam', expectedGames: 5 },
  { source: 'mobygames', name: 'BBC Micro', expectedGames: 1373 },
  { source: 'mobygames', name: 'BeOS', expectedGames: 43 },
  { source: 'mobygames', name: 'BlackBerry', expectedGames: 446 },
  { source: 'mobygames', name: 'Blacknut', expectedGames: 501 },
  { source: 'mobygames', name: 'Blu-ray Disc Player', expectedGames: 26 },
  { source: 'mobygames', name: 'BREW', expectedGames: 421 },
  { source: 'mobygames', name: 'Browser', expectedGames: 7102 },
  { source: 'mobygames', name: 'Bubble', expectedGames: 2 },
  { source: 'mobygames', name: 'Camputers Lynx', expectedGames: 18 },
  { source: 'mobygames', name: 'Casio FP-1000/1100', expectedGames: 4 },
  { source: 'mobygames', name: 'Casio Loopy', expectedGames: 11 },
  { source: 'mobygames', name: 'Casio Programmable Calculator', expectedGames: 4 },
  { source: 'mobygames', name: 'Casio PV-1000', expectedGames: 14 },
  { source: 'mobygames', name: 'CD-i', expectedGames: 217 },
  { source: 'mobygames', name: 'CDTV', expectedGames: 55 },
  { source: 'mobygames', name: 'Champion 2711', expectedGames: 5 },
  { source: 'mobygames', name: 'Channel F', expectedGames: 30 },
  { source: 'mobygames', name: 'ClickStart', expectedGames: 14 },
  { source: 'mobygames', name: 'Coleco Adam', expectedGames: 39 },
  { source: 'mobygames', name: 'ColecoVision', expectedGames: 168 },
  { source: 'mobygames', name: 'Colour Genie', expectedGames: 14 },
  { source: 'mobygames', name: 'Commodore 128', expectedGames: 30 },
  { source: 'mobygames', name: 'Commodore 16, Plus/4', expectedGames: 514 },
  { source: 'mobygames', name: 'Commodore 64', expectedGames: 5755 },
  { source: 'mobygames', name: 'Commodore PET/CBM', expectedGames: 834 },
  { source: 'mobygames', name: 'Compal 80', expectedGames: 1 },
  { source: 'mobygames', name: 'Compucolor I', expectedGames: 3 },
  { source: 'mobygames', name: 'Compucolor II', expectedGames: 23 },
  { source: 'mobygames', name: 'Compucorp Programmable Calculator', expectedGames: 7 },
  { source: 'mobygames', name: 'COSMAC', expectedGames: 83 },
  { source: 'mobygames', name: 'CP/M', expectedGames: 78 },
  { source: 'mobygames', name: 'CreatiVision', expectedGames: 5 },
  { source: 'mobygames', name: 'Cybervision', expectedGames: 11 },
  { source: 'mobygames', name: 'DAI', expectedGames: 2 },
  { source: 'mobygames', name: 'Danger OS', expectedGames: 1 },
  { source: 'mobygames', name: 'Dedicated console', expectedGames: 627 },
  { source: 'mobygames', name: 'Dedicated handheld', expectedGames: 1007 },
  { source: 'mobygames', name: 'Didj', expectedGames: 2 },
  { source: 'mobygames', name: 'digiBlast', expectedGames: 10 },
  { source: 'mobygames', name: 'DoJa', expectedGames: 321 },
  { source: 'mobygames', name: 'DOS', expectedGames: 8463 },
  { source: 'mobygames', name: 'Dragon 32/64', expectedGames: 677 },
  { source: 'mobygames', name: 'Dreamcast', expectedGames: 612 },
  { source: 'mobygames', name: 'DVD Player', expectedGames: 791 },
  { source: 'mobygames', name: 'ECD Micromind', expectedGames: 2 },
  { source: 'mobygames', name: 'Electron', expectedGames: 686 },
  { source: 'mobygames', name: 'Enterprise', expectedGames: 31 },
  { source: 'mobygames', name: 'Epoch Cassette Vision', expectedGames: 4 },
  { source: 'mobygames', name: 'Epoch Game Pocket Computer', expectedGames: 4 },
  { source: 'mobygames', name: 'Epoch Super Cassette Vision', expectedGames: 13 },
  { source: 'mobygames', name: 'Evercade', expectedGames: 97 },
  { source: 'mobygames', name: 'Exelvision', expectedGames: 9 },
  { source: 'mobygames', name: 'ExEn', expectedGames: 48 },
  { source: 'mobygames', name: 'Exidy Sorcerer', expectedGames: 85 },
  { source: 'mobygames', name: 'Feature phone', expectedGames: 4 },
  { source: 'mobygames', name: 'Fire OS', expectedGames: 127 },
  { source: 'mobygames', name: 'FM Towns', expectedGames: 509 },
  { source: 'mobygames', name: 'FM-7', expectedGames: 418 },
  { source: 'mobygames', name: 'Freebox', expectedGames: 24 },
  { source: 'mobygames', name: 'FreeBSD', expectedGames: 14 },
  { source: 'mobygames', name: 'G-cluster', expectedGames: 3 },
  { source: 'mobygames', name: 'Galaksija', expectedGames: 17 },
  { source: 'mobygames', name: 'Game Boy', expectedGames: 890 },
  { source: 'mobygames', name: 'Game Boy Advance', expectedGames: 1285 },
  { source: 'mobygames', name: 'Game Boy Color', expectedGames: 766 },
  { source: 'mobygames', name: 'Game Gear', expectedGames: 369 },
  { source: 'mobygames', name: 'Game Wave', expectedGames: 14 },
  { source: 'mobygames', name: 'Game.Com', expectedGames: 22 },
  { source: 'mobygames', name: 'GameCube', expectedGames: 635 },
  { source: 'mobygames', name: 'GameStick', expectedGames: 27 },
  { source: 'mobygames', name: 'Genesis', expectedGames: 1075 },
  { source: 'mobygames', name: 'GIMINI', expectedGames: 8 },
  { source: 'mobygames', name: 'Gizmondo', expectedGames: 17 },
  { source: 'mobygames', name: 'Gloud', expectedGames: 101 },
  { source: 'mobygames', name: 'Glulx', expectedGames: 10 },
  { source: 'mobygames', name: 'GNEX', expectedGames: 4 },
  { source: 'mobygames', name: 'GP2X', expectedGames: 41 },
  { source: 'mobygames', name: 'GP2X Wiz', expectedGames: 21 },
  { source: 'mobygames', name: 'GP32', expectedGames: 20 },
  { source: 'mobygames', name: 'GVM', expectedGames: 4 },
  { source: 'mobygames', name: 'HD DVD Player', expectedGames: 4 },
  { source: 'mobygames', name: 'Heath/Zenith H8/H89', expectedGames: 25 },
  { source: 'mobygames', name: 'Heathkit H11', expectedGames: 5 },
  { source: 'mobygames', name: 'Hitachi Basic Master', expectedGames: 8 },
  { source: 'mobygames', name: 'Hitachi Basic Master Level 3', expectedGames: 29 },
  { source: 'mobygames', name: 'Hitachi H68/TR', expectedGames: 14 },
  { source: 'mobygames', name: 'Hitachi S1', expectedGames: 30 },
  { source: 'mobygames', name: 'HP 9800', expectedGames: 2 },
  { source: 'mobygames', name: 'HP Oscilloscope', expectedGames: 3 },
  { source: 'mobygames', name: 'HP Programmable Calculator', expectedGames: 72 },
  { source: 'mobygames', name: 'HP Series 80', expectedGames: 2 },
  { source: 'mobygames', name: 'Hugo', expectedGames: 1 },
  { source: 'mobygames', name: 'HyperScan', expectedGames: 5 },
  { source: 'mobygames', name: 'IBM 5100', expectedGames: 5 },
  { source: 'mobygames', name: 'Ideal-Computer', expectedGames: 3 },
  { source: 'mobygames', name: 'iiRcade', expectedGames: 62 },
  { source: 'mobygames', name: 'Intel 8008', expectedGames: 6 },
  { source: 'mobygames', name: 'Intel 8080', expectedGames: 86 },
  { source: 'mobygames', name: 'Intel 8086 / 8088', expectedGames: 2 },
  { source: 'mobygames', name: 'Intellivision', expectedGames: 131 },
  { source: 'mobygames', name: 'Interact Model One', expectedGames: 7 },
  { source: 'mobygames', name: 'Interton Video 2000', expectedGames: 5 },
  { source: 'mobygames', name: 'iPad', expectedGames: 12794 },
  { source: 'mobygames', name: 'iPhone', expectedGames: 13818 },
  { source: 'mobygames', name: 'iPod Classic', expectedGames: 33 },
  { source: 'mobygames', name: 'J2ME', expectedGames: 1355 },
  { source: 'mobygames', name: 'Jaguar', expectedGames: 111 },
  { source: 'mobygames', name: 'Jolt', expectedGames: 2 },
  { source: 'mobygames', name: 'Jupiter Ace', expectedGames: 40 },
  { source: 'mobygames', name: 'KaiOS', expectedGames: 12 },
  { source: 'mobygames', name: 'KIM-1', expectedGames: 36 },
  { source: 'mobygames', name: 'Kindle Classic', expectedGames: 21 },
  { source: 'mobygames', name: 'Laser 200', expectedGames: 7 },
  { source: 'mobygames', name: 'LaserActive', expectedGames: 32 },
  { source: 'mobygames', name: 'LeapFrog Explorer', expectedGames: 6 },
  { source: 'mobygames', name: 'Leapster', expectedGames: 50 },
  { source: 'mobygames', name: 'LeapTV', expectedGames: 15 },
  { source: 'mobygames', name: 'Linux', expectedGames: 12738 },
  { source: 'mobygames', name: 'Lkit-16', expectedGames: 12 },
  { source: 'mobygames', name: 'Luna', expectedGames: 142 },
  { source: 'mobygames', name: 'Lynx', expectedGames: 100 },
  { source: 'mobygames', name: 'Macintosh', expectedGames: 23586 },
  { source: 'mobygames', name: 'Maemo', expectedGames: 17 },
  { source: 'mobygames', name: 'Magic Leap', expectedGames: 15 },
  { source: 'mobygames', name: 'Mainframe', expectedGames: 682 },
  { source: 'mobygames', name: 'Marvel 2000', expectedGames: 1 },
  { source: 'mobygames', name: 'Matsushita/Panasonic JR', expectedGames: 22 },
  { source: 'mobygames', name: 'Mattel Aquarius', expectedGames: 21 },
  { source: 'mobygames', name: 'MeeGo', expectedGames: 34 },
  { source: 'mobygames', name: 'Memotech MTX', expectedGames: 28 },
  { source: 'mobygames', name: 'Meritum', expectedGames: 12 },
  { source: 'mobygames', name: 'Microbee', expectedGames: 14 },
  { source: 'mobygames', name: 'Microtan 65', expectedGames: 2 },
  { source: 'mobygames', name: 'Microvision', expectedGames: 12 },
  { source: 'mobygames', name: 'Mitsubishi Multi-8', expectedGames: 8 },
  { source: 'mobygames', name: 'Modular Game System', expectedGames: 12 },
  { source: 'mobygames', name: 'Mophun', expectedGames: 17 },
  { source: 'mobygames', name: 'MOS Technology 6502', expectedGames: 15 },
  { source: 'mobygames', name: 'Motorola 6800', expectedGames: 43 },
  { source: 'mobygames', name: 'Motorola 68k', expectedGames: 2 },
  { source: 'mobygames', name: 'MRE', expectedGames: 10 },
  { source: 'mobygames', name: 'MSX', expectedGames: 1501 },
  { source: 'mobygames', name: 'N-Gage', expectedGames: 64 },
  { source: 'mobygames', name: 'N-Gage (service)', expectedGames: 28 },
  { source: 'mobygames', name: 'Nascom', expectedGames: 23 },
  { source: 'mobygames', name: 'NEC TK-80', expectedGames: 48 },
  { source: 'mobygames', name: 'Neo Geo', expectedGames: 131 },
  { source: 'mobygames', name: 'Neo Geo CD', expectedGames: 101 },
  { source: 'mobygames', name: 'Neo Geo Pocket', expectedGames: 10 },
  { source: 'mobygames', name: 'Neo Geo Pocket Color', expectedGames: 76 },
  { source: 'mobygames', name: 'Neo Geo X', expectedGames: 7 },
  { source: 'mobygames', name: 'NES', expectedGames: 1658 },
  { source: 'mobygames', name: 'NetBSD', expectedGames: 1 },
  { source: 'mobygames', name: 'New Nintendo 3DS', expectedGames: 126 },
  { source: 'mobygames', name: 'NewBrain', expectedGames: 4 },
  { source: 'mobygames', name: 'Newton', expectedGames: 7 },
  { source: 'mobygames', name: 'Nintendo 3DS', expectedGames: 1696 },
  { source: 'mobygames', name: 'Nintendo 64', expectedGames: 393 },
  { source: 'mobygames', name: 'Nintendo DS', expectedGames: 2406 },
  { source: 'mobygames', name: 'Nintendo DSi', expectedGames: 644 },
  { source: 'mobygames', name: 'Nintendo Switch', expectedGames: 13858 },
  { source: 'mobygames', name: 'Nintendo Switch 2', expectedGames: 299 },
  { source: 'mobygames', name: 'North Star', expectedGames: 64 },
  { source: 'mobygames', name: 'Noval 760', expectedGames: 2 },
  { source: 'mobygames', name: 'Nuon', expectedGames: 7 },
  { source: 'mobygames', name: 'Oculus Go', expectedGames: 263 },
  { source: 'mobygames', name: 'Odyssey', expectedGames: 22 },
  { source: 'mobygames', name: 'Odyssey 2', expectedGames: 107 },
  { source: 'mobygames', name: 'Ohio Scientific', expectedGames: 160 },
  { source: 'mobygames', name: 'OnLive', expectedGames: 144 },
  { source: 'mobygames', name: 'OOParts', expectedGames: 189 },
  { source: 'mobygames', name: 'OpenBSD', expectedGames: 1 },
  { source: 'mobygames', name: 'Orao', expectedGames: 3 },
  { source: 'mobygames', name: 'Oric', expectedGames: 138 },
  { source: 'mobygames', name: 'OS/2', expectedGames: 67 },
  { source: 'mobygames', name: 'Ouya', expectedGames: 255 },
  { source: 'mobygames', name: 'Palm OS', expectedGames: 216 },
  { source: 'mobygames', name: 'Pandora', expectedGames: 15 },
  { source: 'mobygames', name: 'PC Booter', expectedGames: 270 },
  { source: 'mobygames', name: 'PC-6001', expectedGames: 149 },
  { source: 'mobygames', name: 'PC-8000', expectedGames: 150 },
  { source: 'mobygames', name: 'PC-88', expectedGames: 690 },
  { source: 'mobygames', name: 'PC-98', expectedGames: 1448 },
  { source: 'mobygames', name: 'PC-FX', expectedGames: 62 },
  { source: 'mobygames', name: 'Pebble', expectedGames: 5 },
  { source: 'mobygames', name: 'Philips P2000', expectedGames: 70 },
  { source: 'mobygames', name: 'Philips VG 5000', expectedGames: 21 },
  { source: 'mobygames', name: 'Photo CD', expectedGames: 2 },
  { source: 'mobygames', name: 'PICO', expectedGames: 36 },
  { source: 'mobygames', name: 'Pippin', expectedGames: 21 },
  { source: 'mobygames', name: 'Playdate', expectedGames: 130 },
  { source: 'mobygames', name: 'Playdia', expectedGames: 1 },
  { source: 'mobygames', name: 'PlayStation', expectedGames: 3253 },
  { source: 'mobygames', name: 'PlayStation 2', expectedGames: 3535 },
  { source: 'mobygames', name: 'PlayStation 3', expectedGames: 5174 },
  { source: 'mobygames', name: 'PlayStation 4', expectedGames: 12190 },
  { source: 'mobygames', name: 'PlayStation 5', expectedGames: 4848 },
  { source: 'mobygames', name: 'PlayStation Now', expectedGames: 126 },
  { source: 'mobygames', name: 'Plex Arcade', expectedGames: 27 },
  { source: 'mobygames', name: 'Pokitto', expectedGames: 66 },
  { source: 'mobygames', name: 'Pokémon Mini', expectedGames: 10 },
  { source: 'mobygames', name: 'Poly-88', expectedGames: 14 },
  { source: 'mobygames', name: 'PS Vita', expectedGames: 2630 },
  { source: 'mobygames', name: 'PSP', expectedGames: 2327 },
  { source: 'mobygames', name: 'Quest', expectedGames: 551 },
  { source: 'mobygames', name: 'RCA Studio II', expectedGames: 21 },
  { source: 'mobygames', name: 'Research Machines 380Z', expectedGames: 6 },
  { source: 'mobygames', name: 'Roku', expectedGames: 20 },
  { source: 'mobygames', name: 'SAM Coupé', expectedGames: 29 },
  { source: 'mobygames', name: 'SC/MP', expectedGames: 15 },
  { source: 'mobygames', name: 'SD-200/270/290', expectedGames: 2 },
  { source: 'mobygames', name: 'SEGA 32X', expectedGames: 41 },
  { source: 'mobygames', name: 'SEGA CD', expectedGames: 216 },
  { source: 'mobygames', name: 'SEGA Master System', expectedGames: 360 },
  { source: 'mobygames', name: 'SEGA Pico', expectedGames: 30 },
  { source: 'mobygames', name: 'SEGA Saturn', expectedGames: 1161 },
  { source: 'mobygames', name: 'SG-1000', expectedGames: 86 },
  { source: 'mobygames', name: 'Sharp MZ-80B/2000/2500', expectedGames: 149 },
  { source: 'mobygames', name: 'Sharp MZ-80K/700/800/1500', expectedGames: 143 },
  { source: 'mobygames', name: 'Sharp Programmable Calculator', expectedGames: 1 },
  { source: 'mobygames', name: 'Sharp X1', expectedGames: 400 },
  { source: 'mobygames', name: 'Sharp X68000', expectedGames: 480 },
  { source: 'mobygames', name: 'Sharp Zaurus', expectedGames: 13 },
  { source: 'mobygames', name: 'Signetics 2650', expectedGames: 2 },
  { source: 'mobygames', name: 'Sinclair QL', expectedGames: 69 },
  { source: 'mobygames', name: 'SK-VM', expectedGames: 4 },
  { source: 'mobygames', name: 'SMC-777', expectedGames: 30 },
  { source: 'mobygames', name: 'SNES', expectedGames: 1335 },
  { source: 'mobygames', name: 'Socrates', expectedGames: 10 },
  { source: 'mobygames', name: 'Sol-20', expectedGames: 184 },
  { source: 'mobygames', name: 'Solaris', expectedGames: 3 },
  { source: 'mobygames', name: 'Sord M5', expectedGames: 25 },
  { source: 'mobygames', name: 'SPC-1000', expectedGames: 3 },
  { source: 'mobygames', name: 'Spectravideo', expectedGames: 35 },
  { source: 'mobygames', name: 'SRI-500/1000', expectedGames: 1 },
  { source: 'mobygames', name: 'Stadia', expectedGames: 307 },
  { source: 'mobygames', name: 'Super A\'can', expectedGames: 5 },
  { source: 'mobygames', name: 'Super Vision 8000', expectedGames: 7 },
  { source: 'mobygames', name: 'SuperGrafx', expectedGames: 7 },
  { source: 'mobygames', name: 'Supervision', expectedGames: 69 },
  { source: 'mobygames', name: 'Sure Shot HD', expectedGames: 6 },
  { source: 'mobygames', name: 'SWTPC 6800', expectedGames: 47 },
  { source: 'mobygames', name: 'Symbian', expectedGames: 463 },
  { source: 'mobygames', name: 'TADS', expectedGames: 11 },
  { source: 'mobygames', name: 'Taito X-55', expectedGames: 2 },
  { source: 'mobygames', name: 'Tatung Einstein', expectedGames: 36 },
  { source: 'mobygames', name: 'Tektronix 4050', expectedGames: 4 },
  { source: 'mobygames', name: 'Tele-Spiel ES-2201', expectedGames: 5 },
  { source: 'mobygames', name: 'Telstar Arcade', expectedGames: 4 },
  { source: 'mobygames', name: 'TempleOS', expectedGames: 16 },
  { source: 'mobygames', name: 'Terminal', expectedGames: 507 },
  { source: 'mobygames', name: 'Thomson MO', expectedGames: 91 },
  { source: 'mobygames', name: 'Thomson TO', expectedGames: 111 },
  { source: 'mobygames', name: 'TI Programmable Calculator', expectedGames: 152 },
  { source: 'mobygames', name: 'TI-99/4A', expectedGames: 245 },
  { source: 'mobygames', name: 'TIC-80', expectedGames: 35 },
  { source: 'mobygames', name: 'Tiki 100', expectedGames: 4 },
  { source: 'mobygames', name: 'TIM', expectedGames: 2 },
  { source: 'mobygames', name: 'Timex Sinclair 2068', expectedGames: 14 },
  { source: 'mobygames', name: 'Tizen', expectedGames: 34 },
  { source: 'mobygames', name: 'Tomahawk F1', expectedGames: 30 },
  { source: 'mobygames', name: 'Tomy Tutor', expectedGames: 19 },
  { source: 'mobygames', name: 'Toshiba Ex-80', expectedGames: 6 },
  { source: 'mobygames', name: 'Toshiba Pasopia', expectedGames: 40 },
  { source: 'mobygames', name: 'Triton', expectedGames: 4 },
  { source: 'mobygames', name: 'TRS-80', expectedGames: 1407 },
  { source: 'mobygames', name: 'TRS-80 CoCo', expectedGames: 1122 },
  { source: 'mobygames', name: 'TRS-80 MC-10', expectedGames: 14 },
  { source: 'mobygames', name: 'TRS-80 Model 100', expectedGames: 6 },
  { source: 'mobygames', name: 'TurboGrafx CD', expectedGames: 419 },
  { source: 'mobygames', name: 'TurboGrafx-16', expectedGames: 308 },
  { source: 'mobygames', name: 'tvOS', expectedGames: 641 },
  { source: 'mobygames', name: 'V.Flash', expectedGames: 10 },
  { source: 'mobygames', name: 'V.Smile', expectedGames: 13 },
  { source: 'mobygames', name: 'Vectrex', expectedGames: 39 },
  { source: 'mobygames', name: 'Versatile', expectedGames: 2 },
  { source: 'mobygames', name: 'VIC-20', expectedGames: 968 },
  { source: 'mobygames', name: 'VideoBrain', expectedGames: 11 },
  { source: 'mobygames', name: 'Videopac+ G7400', expectedGames: 39 },
  { source: 'mobygames', name: 'Virtual Boy', expectedGames: 28 },
  { source: 'mobygames', name: 'VIS', expectedGames: 8 },
  { source: 'mobygames', name: 'visionOS', expectedGames: 27 },
  { source: 'mobygames', name: 'Wang 2200', expectedGames: 52 },
  { source: 'mobygames', name: 'watchOS', expectedGames: 30 },
  { source: 'mobygames', name: 'webOS', expectedGames: 79 },
  { source: 'mobygames', name: 'Wii', expectedGames: 2635 },
  { source: 'mobygames', name: 'Wii U', expectedGames: 1391 },
  { source: 'mobygames', name: 'Windows', expectedGames: 84808 },
  { source: 'mobygames', name: 'Windows 16-bit', expectedGames: 2282 },
  { source: 'mobygames', name: 'Windows Apps', expectedGames: 3002 },
  { source: 'mobygames', name: 'Windows Mobile', expectedGames: 347 },
  { source: 'mobygames', name: 'Windows Phone', expectedGames: 867 },
  { source: 'mobygames', name: 'WIPI', expectedGames: 13 },
  { source: 'mobygames', name: 'WonderSwan', expectedGames: 108 },
  { source: 'mobygames', name: 'WonderSwan Color', expectedGames: 50 },
  { source: 'mobygames', name: 'XaviXPORT', expectedGames: 4 },
  { source: 'mobygames', name: 'Xbox', expectedGames: 1068 },
  { source: 'mobygames', name: 'Xbox 360', expectedGames: 5008 },
  { source: 'mobygames', name: 'Xbox Cloud Gaming', expectedGames: 537 },
  { source: 'mobygames', name: 'Xbox One', expectedGames: 9141 },
  { source: 'mobygames', name: 'Xbox Series', expectedGames: 5112 },
  { source: 'mobygames', name: 'Xerox Alto', expectedGames: 10 },
  { source: 'mobygames', name: 'Z-machine', expectedGames: 45 },
  { source: 'mobygames', name: 'Zeebo', expectedGames: 58 },
  { source: 'mobygames', name: 'Zilog Z80', expectedGames: 51 },
  { source: 'mobygames', name: 'Zilog Z8000', expectedGames: 1 },
  { source: 'mobygames', name: 'Zodiac', expectedGames: 19 },
  { source: 'mobygames', name: 'Zune', expectedGames: 6 },
  { source: 'mobygames', name: 'ZX Spectrum', expectedGames: 3683 },
  { source: 'mobygames', name: 'ZX Spectrum Next', expectedGames: 73 },
  { source: 'mobygames', name: 'ZX80', expectedGames: 15 },
  { source: 'mobygames', name: 'ZX81', expectedGames: 311 },
];
