import type { PlatformStatus } from '../domain/platform/platform-catalog.js';
import type { PlatformFamily, PlatformType } from '../domain/shared/platform.js';

interface PlatformSeedEntry {
  readonly id: string;
  readonly name: string;
  readonly company: string;
  readonly releaseYear: number | null;
  readonly status: PlatformStatus;
  readonly family: PlatformFamily | null;
  readonly type: PlatformType | null;
}

export const PLATFORM_SEED_DATA: readonly PlatformSeedEntry[] = [
  // ── Nintendo — Home Consoles ──────────────────────────────────────
  {
    id: 'nintendo-entertainment-system',
    name: 'Nintendo Entertainment System',
    company: 'Nintendo',
    releaseYear: 1983,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'super-nintendo-entertainment-system',
    name: 'Super Nintendo Entertainment System',
    company: 'Nintendo',
    releaseYear: 1990,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'nintendo-64',
    name: 'Nintendo 64',
    company: 'Nintendo',
    releaseYear: 1996,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'nintendo-gamecube',
    name: 'Nintendo GameCube',
    company: 'Nintendo',
    releaseYear: 2001,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'wii',
    name: 'Wii',
    company: 'Nintendo',
    releaseYear: 2006,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'wii-u',
    name: 'Wii U',
    company: 'Nintendo',
    releaseYear: 2012,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },

  // ── Nintendo — Hybrid / Current ───────────────────────────────────
  {
    id: 'nintendo-switch',
    name: 'Nintendo Switch',
    company: 'Nintendo',
    releaseYear: 2017,
    status: 'active',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'nintendo-switch-lite',
    name: 'Nintendo Switch Lite',
    company: 'Nintendo',
    releaseYear: 2019,
    status: 'active',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'nintendo-switch-2',
    name: 'Nintendo Switch 2',
    company: 'Nintendo',
    releaseYear: 2025,
    status: 'active',
    family: 'Nintendo',
    type: 'console',
  },

  // ── Nintendo — Handhelds ──────────────────────────────────────────
  {
    id: 'game-boy',
    name: 'Game Boy',
    company: 'Nintendo',
    releaseYear: 1989,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'game-boy-color',
    name: 'Game Boy Color',
    company: 'Nintendo',
    releaseYear: 1998,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'game-boy-advance',
    name: 'Game Boy Advance',
    company: 'Nintendo',
    releaseYear: 2001,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'game-boy-advance-sp',
    name: 'Game Boy Advance SP',
    company: 'Nintendo',
    releaseYear: 2003,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'nintendo-ds',
    name: 'Nintendo DS',
    company: 'Nintendo',
    releaseYear: 2004,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'nintendo-ds-lite',
    name: 'Nintendo DS Lite',
    company: 'Nintendo',
    releaseYear: 2006,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'nintendo-dsi',
    name: 'Nintendo DSi',
    company: 'Nintendo',
    releaseYear: 2008,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'nintendo-3ds',
    name: 'Nintendo 3DS',
    company: 'Nintendo',
    releaseYear: 2011,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'nintendo-3ds-xl',
    name: 'Nintendo 3DS XL',
    company: 'Nintendo',
    releaseYear: 2012,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'nintendo-2ds',
    name: 'Nintendo 2DS',
    company: 'Nintendo',
    releaseYear: 2013,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'new-nintendo-3ds',
    name: 'New Nintendo 3DS',
    company: 'Nintendo',
    releaseYear: 2014,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },
  {
    id: 'new-nintendo-2ds-xl',
    name: 'New Nintendo 2DS XL',
    company: 'Nintendo',
    releaseYear: 2017,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'handheld',
  },

  // ── Nintendo — Virtual Console / Mini ─────────────────────────────
  {
    id: 'nintendo-classic-mini',
    name: 'Nintendo Classic Mini: NES',
    company: 'Nintendo',
    releaseYear: 2016,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'super-nintendo-classic-mini',
    name: 'Super Nintendo Classic Mini',
    company: 'Nintendo',
    releaseYear: 2017,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'nintendo-classic-mini-famicom',
    name: 'Nintendo Classic Mini: Famicom',
    company: 'Nintendo',
    releaseYear: 2016,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'super-nintendo-classic-mini-super-famicom',
    name: 'Super Nintendo Classic Mini: Super Famicom',
    company: 'Nintendo',
    releaseYear: 2017,
    status: 'discontinued',
    family: 'Nintendo',
    type: 'console',
  },

  // ── Sony — PlayStation Home ───────────────────────────────────────
  {
    id: 'playstation',
    name: 'PlayStation',
    company: 'Sony',
    releaseYear: 1994,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-2',
    name: 'PlayStation 2',
    company: 'Sony',
    releaseYear: 2000,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-3',
    name: 'PlayStation 3',
    company: 'Sony',
    releaseYear: 2006,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-4',
    name: 'PlayStation 4',
    company: 'Sony',
    releaseYear: 2013,
    status: 'active',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-4-pro',
    name: 'PlayStation 4 Pro',
    company: 'Sony',
    releaseYear: 2016,
    status: 'active',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-5',
    name: 'PlayStation 5',
    company: 'Sony',
    releaseYear: 2020,
    status: 'active',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-5-digital-edition',
    name: 'PlayStation 5 Digital Edition',
    company: 'Sony',
    releaseYear: 2020,
    status: 'active',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-5-slim',
    name: 'PlayStation 5 Slim',
    company: 'Sony',
    releaseYear: 2023,
    status: 'active',
    family: 'PlayStation',
    type: 'console',
  },
  {
    id: 'playstation-5-pro',
    name: 'PlayStation 5 Pro',
    company: 'Sony',
    releaseYear: 2024,
    status: 'active',
    family: 'PlayStation',
    type: 'console',
  },

  // ── Sony — Handhelds ──────────────────────────────────────────────
  {
    id: 'playstation-portable',
    name: 'PlayStation Portable',
    company: 'Sony',
    releaseYear: 2004,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'handheld',
  },
  {
    id: 'playstation-portable-slim',
    name: 'PlayStation Portable Slim',
    company: 'Sony',
    releaseYear: 2007,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'handheld',
  },
  {
    id: 'playstation-portable-street',
    name: 'PSP Street',
    company: 'Sony',
    releaseYear: 2011,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'handheld',
  },
  {
    id: 'playstation-vita',
    name: 'PlayStation Vita',
    company: 'Sony',
    releaseYear: 2011,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'handheld',
  },
  {
    id: 'playstation-vita-slim',
    name: 'PlayStation Vita Slim',
    company: 'Sony',
    releaseYear: 2013,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'handheld',
  },

  // ── Microsoft — Xbox ──────────────────────────────────────────────
  {
    id: 'xbox',
    name: 'Xbox',
    company: 'Microsoft',
    releaseYear: 2001,
    status: 'discontinued',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-360',
    name: 'Xbox 360',
    company: 'Microsoft',
    releaseYear: 2005,
    status: 'discontinued',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-360-s',
    name: 'Xbox 360 S',
    company: 'Microsoft',
    releaseYear: 2010,
    status: 'discontinued',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-360-e',
    name: 'Xbox 360 E',
    company: 'Microsoft',
    releaseYear: 2013,
    status: 'discontinued',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-one',
    name: 'Xbox One',
    company: 'Microsoft',
    releaseYear: 2013,
    status: 'active',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-one-s',
    name: 'Xbox One S',
    company: 'Microsoft',
    releaseYear: 2016,
    status: 'active',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-one-x',
    name: 'Xbox One X',
    company: 'Microsoft',
    releaseYear: 2017,
    status: 'active',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-series-x',
    name: 'Xbox Series X',
    company: 'Microsoft',
    releaseYear: 2020,
    status: 'active',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-series-s',
    name: 'Xbox Series S',
    company: 'Microsoft',
    releaseYear: 2020,
    status: 'active',
    family: 'Xbox',
    type: 'console',
  },
  {
    id: 'xbox-series-x-digital',
    name: 'Xbox Series X Digital Edition',
    company: 'Microsoft',
    releaseYear: 2024,
    status: 'active',
    family: 'Xbox',
    type: 'console',
  },

  // ── Sega — Consoles ───────────────────────────────────────────────
  {
    id: 'sg-1000',
    name: 'SG-1000',
    company: 'Sega',
    releaseYear: 1983,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-master-system',
    name: 'Sega Master System',
    company: 'Sega',
    releaseYear: 1985,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-genesis',
    name: 'Sega Genesis',
    company: 'Sega',
    releaseYear: 1988,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-mega-drive',
    name: 'Sega Mega Drive',
    company: 'Sega',
    releaseYear: 1988,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-genesis-2',
    name: 'Sega Genesis 2',
    company: 'Sega',
    releaseYear: 1993,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-mega-drive-2',
    name: 'Sega Mega Drive 2',
    company: 'Sega',
    releaseYear: 1993,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-32x',
    name: 'Sega 32X',
    company: 'Sega',
    releaseYear: 1994,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-cd',
    name: 'Sega CD',
    company: 'Sega',
    releaseYear: 1991,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-mega-cd',
    name: 'Sega Mega CD',
    company: 'Sega',
    releaseYear: 1991,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-saturn',
    name: 'Sega Saturn',
    company: 'Sega',
    releaseYear: 1994,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-dreamcast',
    name: 'Sega Dreamcast',
    company: 'Sega',
    releaseYear: 1998,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },

  // ── Sega — Handhelds ──────────────────────────────────────────────
  {
    id: 'sega-game-gear',
    name: 'Sega Game Gear',
    company: 'Sega',
    releaseYear: 1990,
    status: 'discontinued',
    family: 'Sega',
    type: 'handheld',
  },
  {
    id: 'sega-genesis-portable',
    name: 'Sega Genesis Portable',
    company: 'Sega',
    releaseYear: 2006,
    status: 'discontinued',
    family: 'Sega',
    type: 'handheld',
  },

  // ── Sega — Mini / Retro ───────────────────────────────────────────
  {
    id: 'sega-genesis-classic',
    name: 'Sega Genesis Classic',
    company: 'Sega',
    releaseYear: 2018,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-mega-drive-mini',
    name: 'Sega Mega Drive Mini',
    company: 'Sega',
    releaseYear: 2019,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-genesis-mini-2',
    name: 'Sega Genesis Mini 2',
    company: 'Sega',
    releaseYear: 2022,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'sega-mega-drive-mini-2',
    name: 'Sega Mega Drive Mini 2',
    company: 'Sega',
    releaseYear: 2022,
    status: 'discontinued',
    family: 'Sega',
    type: 'console',
  },

  // ── Atari — Home ──────────────────────────────────────────────────
  {
    id: 'atari-2600',
    name: 'Atari 2600',
    company: 'Atari',
    releaseYear: 1977,
    status: 'discontinued',
    family: 'Atari',
    type: 'console',
  },
  {
    id: 'atari-5200',
    name: 'Atari 5200',
    company: 'Atari',
    releaseYear: 1982,
    status: 'discontinued',
    family: 'Atari',
    type: 'console',
  },
  {
    id: 'atari-7800',
    name: 'Atari 7800',
    company: 'Atari',
    releaseYear: 1986,
    status: 'discontinued',
    family: 'Atari',
    type: 'console',
  },
  {
    id: 'atari-jaguar',
    name: 'Atari Jaguar',
    company: 'Atari',
    releaseYear: 1993,
    status: 'discontinued',
    family: 'Atari',
    type: 'console',
  },
  {
    id: 'atari-jaguar-cd',
    name: 'Atari Jaguar CD',
    company: 'Atari',
    releaseYear: 1995,
    status: 'discontinued',
    family: 'Atari',
    type: 'console',
  },
  {
    id: 'atari-lynx',
    name: 'Atari Lynx',
    company: 'Atari',
    releaseYear: 1989,
    status: 'discontinued',
    family: 'Atari',
    type: 'handheld',
  },
  {
    id: 'atari-lynx-ii',
    name: 'Atari Lynx II',
    company: 'Atari',
    releaseYear: 1991,
    status: 'discontinued',
    family: 'Atari',
    type: 'handheld',
  },

  // ── Atari — Modern ────────────────────────────────────────────────
  {
    id: 'atari-vcs',
    name: 'Atari VCS',
    company: 'Atari',
    releaseYear: 2021,
    status: 'active',
    family: 'Atari',
    type: 'console',
  },

  // ── PC ────────────────────────────────────────────────────────────
  {
    id: 'pc-windows',
    name: 'PC (Windows)',
    company: 'Microsoft',
    releaseYear: 1995,
    status: 'active',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-mac',
    name: 'PC (macOS)',
    company: 'Apple',
    releaseYear: 1984,
    status: 'active',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-linux',
    name: 'PC (Linux)',
    company: 'Various',
    releaseYear: 1991,
    status: 'active',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-dos',
    name: 'PC (DOS)',
    company: 'IBM',
    releaseYear: 1981,
    status: 'discontinued',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-amiga',
    name: 'Amiga',
    company: 'Commodore',
    releaseYear: 1985,
    status: 'discontinued',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-commodore-64',
    name: 'Commodore 64',
    company: 'Commodore',
    releaseYear: 1982,
    status: 'discontinued',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-zx-spectrum',
    name: 'ZX Spectrum',
    company: 'Sinclair Research',
    releaseYear: 1982,
    status: 'discontinued',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-msx',
    name: 'MSX',
    company: 'Microsoft',
    releaseYear: 1983,
    status: 'discontinued',
    family: 'PC',
    type: 'computer',
  },
  {
    id: 'pc-turbo-grafx-16',
    name: 'TurboGrafx-16',
    company: 'NEC',
    releaseYear: 1987,
    status: 'discontinued',
    family: 'PC',
    type: 'console',
  },
  {
    id: 'pc-engine',
    name: 'PC Engine',
    company: 'NEC',
    releaseYear: 1987,
    status: 'discontinued',
    family: 'PC',
    type: 'console',
  },
  {
    id: 'pc-engine-turbo',
    name: 'PC Engine Turbo',
    company: 'NEC',
    releaseYear: 1991,
    status: 'discontinued',
    family: 'PC',
    type: 'console',
  },
  {
    id: 'pc-engine-super-cd-rom',
    name: 'PC Engine Super CD-ROM²',
    company: 'NEC',
    releaseYear: 1991,
    status: 'discontinued',
    family: 'PC',
    type: 'console',
  },
  {
    id: 'pc-engine-duo',
    name: 'PC Engine Duo',
    company: 'NEC',
    releaseYear: 1991,
    status: 'discontinued',
    family: 'PC',
    type: 'console',
  },

  // ── Bandai ────────────────────────────────────────────────────────
  {
    id: 'wonderswan',
    name: 'WonderSwan',
    company: 'Bandai',
    releaseYear: 1999,
    status: 'discontinued',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'wonderswan-color',
    name: 'WonderSwan Color',
    company: 'Bandai',
    releaseYear: 2000,
    status: 'discontinued',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'swan-crystal',
    name: 'Swan Crystal',
    company: 'Bandai',
    releaseYear: 2002,
    status: 'discontinued',
    family: 'Other',
    type: 'handheld',
  },

  // ── SNK ───────────────────────────────────────────────────────────
  {
    id: 'neo-geo',
    name: 'Neo Geo AES',
    company: 'SNK',
    releaseYear: 1990,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'neo-geo-cd',
    name: 'Neo Geo CD',
    company: 'SNK',
    releaseYear: 1994,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'neo-geo-pocket',
    name: 'Neo Geo Pocket',
    company: 'SNK',
    releaseYear: 1998,
    status: 'discontinued',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'neo-geo-pocket-color',
    name: 'Neo Geo Pocket Color',
    company: 'SNK',
    releaseYear: 1999,
    status: 'discontinued',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'neo-geo-mini',
    name: 'Neo Geo Mini',
    company: 'SNK',
    releaseYear: 2018,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'neo-geo-arcade-stick-pro',
    name: 'Neo Geo Arcade Stick Pro',
    company: 'SNK',
    releaseYear: 2019,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── NEC / Hudson ──────────────────────────────────────────────────
  {
    id: 'turbografx-16-mini',
    name: 'TurboGrafx-16 Mini',
    company: 'Konami',
    releaseYear: 2020,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── The3DO Company ────────────────────────────────────────────────
  {
    id: '3do',
    name: '3DO Interactive Multiplayer',
    company: 'The3DO Company',
    releaseYear: 1993,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Philips ───────────────────────────────────────────────────────
  {
    id: 'cd-i',
    name: 'CD-i',
    company: 'Philips',
    releaseYear: 1991,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Casio ─────────────────────────────────────────────────────────
  {
    id: 'pv-1000',
    name: 'PV-1000',
    company: 'Casio',
    releaseYear: 1983,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── GCE / Milton Bradley ──────────────────────────────────────────
  {
    id: 'vectrex',
    name: 'Vectrex',
    company: 'GCE',
    releaseYear: 1982,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Bally / Astrocade ─────────────────────────────────────────────
  {
    id: 'astrocade',
    name: 'Astrocade',
    company: 'Bally',
    releaseYear: 1977,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Fairchild ─────────────────────────────────────────────────────
  {
    id: 'channel-f',
    name: 'Fairchild Channel F',
    company: 'Fairchild',
    releaseYear: 1976,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Magnavox ──────────────────────────────────────────────────────
  {
    id: 'odyssey',
    name: 'Magnavox Odyssey',
    company: 'Magnavox',
    releaseYear: 1972,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'odyssey-2',
    name: 'Magnavox Odyssey²',
    company: 'Magnavox',
    releaseYear: 1978,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Intellivision ─────────────────────────────────────────────────
  {
    id: 'intellivision',
    name: 'Intellivision',
    company: 'Mattel',
    releaseYear: 1979,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Coleco ────────────────────────────────────────────────────────
  {
    id: 'coleco-vision',
    name: 'ColecoVision',
    company: 'Coleco',
    releaseYear: 1982,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Emerson ───────────────────────────────────────────────────────
  {
    id: 'coleco-adam',
    name: 'Coleco Adam',
    company: 'Coleco',
    releaseYear: 1983,
    status: 'discontinued',
    family: 'Other',
    type: 'computer',
  },

  // ── Apple — Mobile ────────────────────────────────────────────────
  {
    id: 'iphone',
    name: 'iPhone',
    company: 'Apple',
    releaseYear: 2007,
    status: 'active',
    family: 'Mobile',
    type: 'mobile',
  },
  {
    id: 'ipad',
    name: 'iPad',
    company: 'Apple',
    releaseYear: 2010,
    status: 'active',
    family: 'Mobile',
    type: 'mobile',
  },

  // ── Android ───────────────────────────────────────────────────────
  {
    id: 'android',
    name: 'Android',
    company: 'Google',
    releaseYear: 2008,
    status: 'active',
    family: 'Mobile',
    type: 'mobile',
  },

  // ── Ouya / Fire TV ────────────────────────────────────────────────
  {
    id: 'ouya',
    name: 'Ouya',
    company: 'Ouya',
    releaseYear: 2013,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'fire-tv',
    name: 'Fire TV',
    company: 'Amazon',
    releaseYear: 2014,
    status: 'active',
    family: 'Other',
    type: 'console',
  },

  // ── Google ────────────────────────────────────────────────────────
  {
    id: 'google-stadia',
    name: 'Google Stadia',
    company: 'Google',
    releaseYear: 2019,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Handheld PCs ──────────────────────────────────────────────────
  {
    id: 'steam-deck',
    name: 'Steam Deck',
    company: 'Valve',
    releaseYear: 2022,
    status: 'active',
    family: 'PC',
    type: 'handheld',
  },
  {
    id: 'steam-deck-oled',
    name: 'Steam Deck OLED',
    company: 'Valve',
    releaseYear: 2023,
    status: 'active',
    family: 'PC',
    type: 'handheld',
  },
  {
    id: 'asus-rog-ally',
    name: 'ASUS ROG Ally',
    company: 'ASUS',
    releaseYear: 2023,
    status: 'active',
    family: 'PC',
    type: 'handheld',
  },
  {
    id: 'asus-rog-ally-x',
    name: 'ASUS ROG Ally X',
    company: 'ASUS',
    releaseYear: 2024,
    status: 'active',
    family: 'PC',
    type: 'handheld',
  },
  {
    id: 'lenovo-legion-go',
    name: 'Lenovo Legion Go',
    company: 'Lenovo',
    releaseYear: 2023,
    status: 'active',
    family: 'PC',
    type: 'handheld',
  },
  {
    id: 'msi-claw',
    name: 'MSI Claw',
    company: 'MSI',
    releaseYear: 2024,
    status: 'active',
    family: 'PC',
    type: 'handheld',
  },

  // ── Retro / Boutique ──────────────────────────────────────────────
  {
    id: 'analogue-pocket',
    name: 'Analogue Pocket',
    company: 'Analogue',
    releaseYear: 2021,
    status: 'active',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'analogue-sg',
    name: 'Analogue Super Nt',
    company: 'Analogue',
    releaseYear: 2018,
    status: 'active',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'analogue-nt',
    name: 'Analogue Nt',
    company: 'Analogue',
    releaseYear: 2015,
    status: 'active',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'analogue-nt-mini',
    name: 'Analogue Nt Mini',
    company: 'Analogue',
    releaseYear: 2017,
    status: 'active',
    family: 'Nintendo',
    type: 'console',
  },
  {
    id: 'analogue-mega-sg',
    name: 'Analogue Mega Sg',
    company: 'Analogue',
    releaseYear: 2019,
    status: 'active',
    family: 'Sega',
    type: 'console',
  },
  {
    id: 'evercade',
    name: 'Evercade',
    company: 'Blaze Entertainment',
    releaseYear: 2020,
    status: 'active',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'evercade-vs',
    name: 'Evercade VS',
    company: 'Blaze Entertainment',
    releaseYear: 2021,
    status: 'active',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'evercade-explorer',
    name: 'Evercade EXP',
    company: 'Blaze Entertainment',
    releaseYear: 2022,
    status: 'active',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'polymega',
    name: 'Polymega',
    company: 'Playmaji',
    releaseYear: 2021,
    status: 'active',
    family: 'Other',
    type: 'console',
  },

  // ── Arcade ────────────────────────────────────────────────────────
  {
    id: 'naomi',
    name: 'Sega NAOMI',
    company: 'Sega',
    releaseYear: 1998,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'naomi-2',
    name: 'Sega NAOMI 2',
    company: 'Sega',
    releaseYear: 2001,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'naomi-gd-rom',
    name: 'Sega NAOMI GD-ROM',
    company: 'Sega',
    releaseYear: 2000,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'model-2',
    name: 'Sega Model 2',
    company: 'Sega',
    releaseYear: 1993,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'model-3',
    name: 'Sega Model 3',
    company: 'Sega',
    releaseYear: 1996,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'chihiro',
    name: 'Sega Chihiro',
    company: 'Sega',
    releaseYear: 2003,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'lindbergh',
    name: 'Sega Lindbergh',
    company: 'Sega',
    releaseYear: 2005,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'ringedge',
    name: 'Sega RingEdge',
    company: 'Sega',
    releaseYear: 2009,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'ringedge-2',
    name: 'Sega RingEdge 2',
    company: 'Sega',
    releaseYear: 2012,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'naomi-mini',
    name: 'Sega Naomi Universal Cabinet',
    company: 'Sega',
    releaseYear: 1999,
    status: 'discontinued',
    family: 'Sega',
    type: 'arcade',
  },
  {
    id: 'cave-cv-1000',
    name: 'CAVE CV-1000',
    company: 'CAVE',
    releaseYear: 2005,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'pgm',
    name: 'PolyGame Master (PGM)',
    company: 'IGS',
    releaseYear: 1997,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'pgm-2',
    name: 'PGM 2',
    company: 'IGS',
    releaseYear: 2008,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'namco-system-22',
    name: 'Namco System 22',
    company: 'Namco',
    releaseYear: 1993,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'namco-system-246',
    name: 'Namco System 246',
    company: 'Namco',
    releaseYear: 2000,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'namco-system-256',
    name: 'Namco System 256',
    company: 'Namco',
    releaseYear: 2003,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'namco-system-357',
    name: 'Namco System 357',
    company: 'Bandai Namco',
    releaseYear: 2007,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'namco-system-369',
    name: 'Namco System 369',
    company: 'Bandai Namco',
    releaseYear: 2010,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'taito-type-x',
    name: 'Taito Type X',
    company: 'Taito',
    releaseYear: 2004,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'taito-type-x-plus',
    name: 'Taito Type X+',
    company: 'Taito',
    releaseYear: 2008,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'taito-type-x2',
    name: 'Taito Type X2',
    company: 'Taito',
    releaseYear: 2010,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },

  // ── SNK — Arcade ──────────────────────────────────────────────────
  {
    id: 'neo-geo-mvs',
    name: 'Neo Geo MVS',
    company: 'SNK',
    releaseYear: 1990,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'neo-geo-hyper-neo-geo-64',
    name: 'Hyper Neo Geo 64',
    company: 'SNK',
    releaseYear: 1997,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'neo-geo-semi-modern',
    name: 'Neo Geo X',
    company: 'SNK',
    releaseYear: 2012,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Konami — Arcade ───────────────────────────────────────────────
  {
    id: 'konami-system-573',
    name: 'Konami System 573',
    company: 'Konami',
    releaseYear: 1999,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'konami-system-e',
    name: 'Konami System E',
    company: 'Konami',
    releaseYear: 1985,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'konami-twinkle',
    name: 'Konami Twinkle',
    company: 'Konami',
    releaseYear: 2002,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },

  // ── Capcom — Arcade ───────────────────────────────────────────────
  {
    id: 'capcom-cps1',
    name: 'Capcom Play System 1 (CPS-1)',
    company: 'Capcom',
    releaseYear: 1988,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'capcom-cps2',
    name: 'Capcom Play System 2 (CPS-2)',
    company: 'Capcom',
    releaseYear: 1993,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },
  {
    id: 'capcom-cps3',
    name: 'Capcom Play System 3 (CPS-3)',
    company: 'Capcom',
    releaseYear: 1996,
    status: 'discontinued',
    family: 'Other',
    type: 'arcade',
  },

  // ── Sony — Arcade ─────────────────────────────────────────────────
  {
    id: 'system-357',
    name: 'Sony System 357',
    company: 'Sony',
    releaseYear: 2007,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'arcade',
  },
  {
    id: 'system-369',
    name: 'Sony System 369',
    company: 'Sony',
    releaseYear: 2010,
    status: 'discontinued',
    family: 'PlayStation',
    type: 'arcade',
  },

  // ── Other / Misc ──────────────────────────────────────────────────
  {
    id: 'n-gage',
    name: 'N-Gage',
    company: 'Nokia',
    releaseYear: 2003,
    status: 'discontinued',
    family: 'Mobile',
    type: 'mobile',
  },
  {
    id: 'n-gage-qd',
    name: 'N-Gage QD',
    company: 'Nokia',
    releaseYear: 2004,
    status: 'discontinued',
    family: 'Mobile',
    type: 'mobile',
  },
  {
    id: 'game-com',
    name: 'Game.com',
    company: 'Tiger Electronics',
    releaseYear: 1997,
    status: 'discontinued',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'turbo-express',
    name: 'TurboExpress',
    company: 'NEC',
    releaseYear: 1990,
    status: 'discontinued',
    family: 'Other',
    type: 'handheld',
  },
  {
    id: 'game-wave',
    name: 'Game Wave',
    company: 'Z-Axis',
    releaseYear: 1995,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'casio-loopy',
    name: 'Casio Loopy',
    company: 'Casio',
    releaseYear: 1995,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'playdia',
    name: 'Playdia',
    company: 'Bandai',
    releaseYear: 1994,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'xavix',
    name: 'Xavix',
    company: 'SSD Company',
    releaseYear: 2004,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'gizmondo',
    name: 'Gizmondo',
    company: 'Tiger Telematics',
    releaseYear: 2005,
    status: 'discontinued',
    family: 'Mobile',
    type: 'handheld',
  },
  {
    id: 'phaedra',
    name: 'Phaedra',
    company: 'Phaedra',
    releaseYear: null,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'zapit-wave',
    name: 'Zapit Game Wave',
    company: 'Zapit',
    releaseYear: 2003,
    status: 'discontinued',
    family: 'Other',
    type: 'console',
  },

  // ── Web / Browser ─────────────────────────────────────────────────
  {
    id: 'flash',
    name: 'Adobe Flash',
    company: 'Adobe',
    releaseYear: 1996,
    status: 'discontinued',
    family: 'PC',
    type: 'web',
  },
  {
    id: 'html5-web',
    name: 'HTML5 Web Browser',
    company: 'Various',
    releaseYear: 2014,
    status: 'active',
    family: 'PC',
    type: 'web',
  },

  // ── Smart TVs ─────────────────────────────────────────────────────
  {
    id: 'smart-tv',
    name: 'Smart TV (various)',
    company: 'Various',
    releaseYear: 2010,
    status: 'active',
    family: 'Other',
    type: 'web',
  },

  // ── Retro Consoles / Plug & Play ──────────────────────────────────
  {
    id: 'atari-flashback',
    name: 'Atari Flashback',
    company: 'Atari',
    releaseYear: 2004,
    status: 'active',
    family: 'Atari',
    type: 'console',
  },
  {
    id: 'segaclassic',
    name: 'Sega Classics',
    company: 'Sega',
    releaseYear: 2018,
    status: 'active',
    family: 'Sega',
    type: 'console',
  },

  // ── Amazon Luna ───────────────────────────────────────────────────
  {
    id: 'amazon-luna',
    name: 'Amazon Luna',
    company: 'Amazon',
    releaseYear: 2020,
    status: 'active',
    family: 'Other',
    type: 'web',
  },

  // ── Nvidia Shield ─────────────────────────────────────────────────
  {
    id: 'nvidia-shield',
    name: 'NVIDIA Shield',
    company: 'NVIDIA',
    releaseYear: 2015,
    status: 'active',
    family: 'Other',
    type: 'console',
  },
  {
    id: 'nvidia-shield-tv',
    name: 'NVIDIA Shield TV',
    company: 'NVIDIA',
    releaseYear: 2017,
    status: 'active',
    family: 'Other',
    type: 'console',
  },

  // ── Xbox Handheld ─────────────────────────────────────────────────
  {
    id: 'xbox-rog-alliance',
    name: 'ROG Ally (Xbox)',
    company: 'Microsoft',
    releaseYear: 2025,
    status: 'active',
    family: 'Xbox',
    type: 'handheld',
  },
] as const;
